# Generated by Django 5.0.3 on 2026-06-15 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('criticality', models.CharField(choices=[('LOW', 'Low Operational Risk'), ('MEDIUM', 'Medium Process Risk'), ('HIGH', 'High Line Stop Risk'), ('CRITICAL', 'Plant Shutdown Risk')], default='MEDIUM', max_length=20)),
                ('health_status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical Alert')], default='HEALTHY', max_length=20)),
                ('health_percentage', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
                ('vibration', models.FloatField()),
                ('rpm', models.FloatField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='dashboard.equipment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
